### PR TITLE
User system lang

### PR DESCRIPTION
**Pull request by buren**

### CODE REVIEW

**Comment by buren** [comment]
cc @bex1 now `data/attributes/system_language` is supported, so we can migrate `language` => `system_language` in the user registration/update forms.

**Comment by bex1** [comment]
@buren WIll switch to system_language as soon as im done with the proxies.
Ill PM you.

One question small question though. Why can't I see system_language in the docs? [https://api.justarrived.se/api_docs/1.0/users/index.html](url)
Is it beacause its not deployed yet or something? 😄

**Comment by buren** [comment]
Yeah the docs will be updated as soon as that version is deployed to that environment

**Comment by bex1** [comment]
Ah I see. So is there a sandbox api docs maybe? For dev purposes.

**Comment by bex1** [comment]
@buren

**Comment by buren** [comment]
Yep there is https://sandbox-api.justarrived.xyz :)

**Pull request merged**
